name : workflow

on:
    push:
        branches: 
            - main
    
       

jobs:
    integration:
        name: Continous Integration
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Lint code
              run: echo "Linting Respository"

            - name: Run Unit Tests
              run: echo "Running Unit Tests"

    build-and-push-ecr-image:
        name: Conituous Delivery
        needs: integration
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Utilities
              run: |
                sudo apt-get update
                sudo apt-get install -y jq unzip
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, tag, and push Docker image to AMAZON ECR
              id: build-image
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                echo "Docker image pushed to ECR: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
                IMAGE_TAG: latest

    continuous-deployment:
        name: Continuous Deployment
        needs: build-and-push-ecr-image
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Debug ECR
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
              run: |
                echo "Registry=$ECR_REGISTRY"
                echo "Repository=$ECR_REPOSITORY"

                aws ecr describe-images \
                --repository-name $ECR_REPOSITORY \
                --region us-east-1

            - name: Pull Latest Image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
              run: |
                docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest

            - name: Stop Existing Container
              run: |
                docker stop networksecurity || true
                docker rm networksecurity || true

            - name: Run Docker Container
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
              run: |
                docker run -d \
                --name networksecurity \
                --restart unless-stopped \
                -p 8080:8000 \
                -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                -e AWS_REGION=us-east-1 \
                -e MONGO_DB_URL="${{ secrets.MONGO_DB_URL }}" \
                -e DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }} \
                $ECR_REGISTRY/$ECR_REPOSITORY:latest

            - name: Verify Deployment
              run: |
                docker ps
                docker images

            - name: Cleanup Docker
              run: |
                docker image prune -af